### ISSUE TITLE
匹配之后能不能有更多的一些功能

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#108]
![2657](https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTK6RRU5A9fFBic9wEicqQjDIJa2PtLsFxYMKnMtnXKSFJRl3bYnYtkuzOdIwfI04aELicYFiadYjztcNg/132-46.jpg) 泽宇.com
---
匹配之后能不能有更多的一些功能

**Comment by airingursb** [comment]
#67 

后续会继续新增有趣的功能
