### ISSUE TITLE
总是不能及时更新对方的日记

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#113]
![1718](https://airing.ursb.me/2life/user/1718/profile_1534820182704.png-2life_face.jpg-46.jpg) JoeyMays
---
总是不能及时更新对方的日记 希望可以新出提醒功能的选项

**Comment by airingursb** [comment]
2.1.3 版本 bug，此功能之前已做，新版本上线了离线日记的功能之后出现的bug。预计下周2.1.4会修复。

**Comment by airingursb** [comment]
已定位，同步策略问题+前端同步时机有问题。
此bug优先级提为P0，务必优先解决。

**Comment by airingursb** [comment]
已在2.0.6版本解决
