### ISSUE TITLE
为什么精准匹配搜索不到？

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#114]
![2123](https://wx.qlogo.cn/mmopen/vi_32/oYFPa0PNp42HM43KqwzsvQUa9tVibNBeSriaRROGyHZuvShKecYmARXpv8iaTtH9z38lVe0bYSNJyffq4T18FKs6A/132-46.jpg) 杰哥
---
062669，我的好友ID，为什么精准匹配，搜索不到？

**Comment by airingursb** [comment]
062669 没有写日记所以匹配不到，这里有提示的。
