### ISSUE TITLE
匹配了好友怎么聊天啊

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#141]
![938](https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83eqRcxg7D4S0UoiaI8cXRJ70M5bTAk1eNdJ5R54rDdMxR1pGwaic8KwzampLOsZestyvLmpPRnTOibDeg/132-46.jpg) Sillywa
---
匹配了好友怎么聊天啊

**Comment by airingursb** [comment]
可以通过写日记进行聊天
