### ISSUE TITLE
想要取消匹配

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#145]
![2003](https://wx.qlogo.cn/mmopen/vi_32/JNagocb2MC4ZzFgSAdJTicicicOmPnuiaH33nyTBpS6Y0eFtnchfsq0jP2rAicd6obzrzc2oL5Cxf74IaI5WslJMDOw/132-46.jpg) AA小胖姚😘 😘
---
想要取消匹配

**Comment by airingursb** [comment]
直接取消就行了- - 
可以考虑加一个新手帮助页面
