### ISSUE TITLE
图片只能看到一部分，这不是我想看到的

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#158]
![468](https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJ4q0zKkfcSMg0zmWIjI7Vicvn2UGx648J03MvLx2P78AnIaTlxuN8fE6Jy5k4dqnw890ia6flaaLcA/132-46.jpg) baymax
---
图片只能看到一部分，这不是我想看到的

**Comment by airingursb** [comment]
已于 2.1.4 中实现
