### ISSUE TITLE
保存不了

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#159]
![468](https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJ4q0zKkfcSMg0zmWIjI7Vicvn2UGx648J03MvLx2P78AnIaTlxuN8fE6Jy5k4dqnw890ia6flaaLcA/132-46.jpg) baymax
---
保存不了

**Comment by airingursb** [comment]
2.1.4 已支持手势保存
