### ISSUE TITLE
测试反馈接口，老板是傻X！

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#161]
![2](https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLFGzibQXskGYg4bEiav4gtcicxdSwt2606BFgF0RCrtRBIeqhc5TQkQjP4vvic1iaImcfEo2hbjCOeeBw/132-46.jpg) 介质
---
测试反馈接口，老板是傻X！

**Comment by zyktrcn** [comment]
测试反馈
