### ISSUE TITLE
匹配功能还可以用完哦，没得机会了嘛

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#163]
![5809](https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJYeuTiaWud7kctPqp1sFicSZlaX98FNZPKk8FVvBKKkg1CfICKL7wIz8c0OPtg3viaKu02Q2j3tr6LA/132-46.jpg) TZX
---
匹配功能还可以用完哦，没得机会了嘛

**Comment by airingursb** [comment]
#165

**Comment by airingursb** [comment]
#160
