### ISSUE TITLE
请问为什么账号匹配不成功呢？

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#165]
![3121](https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83erJEqa95HvFXEOVXPzjCfwx7pzNSyscLdRkdMyJSEgCQz4pSLeW0QzCW2edTql1Sbicicew6rfYdiawQ/132-46.jpg) 、时迁
---
请问为什么账号匹配不成功呢？

**Comment by airingursb** [comment]
#155
