### ISSUE TITLE
需要截图功能，目前截图会缺少很多内容

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#168]
![4395](https://wx.qlogo.cn/mmopen/vi_32/b6PdJ9k2Ag1zViaGCyquPkqibNyRKQtic7iaHBPFiaX537ptgF9KMCibqbrxsOficfGocEjLjdMicVwlJIsxSw5FYaNJBA/132-46.jpg) cos ²x+sin ²x=1
---
需要截图功能，目前截图会缺少很多内容

**Comment by airingursb** [comment]
已于2.1.10中实现
