### ISSUE TITLE
写日记界面，输入不能用拼音打字

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#170]
![6182](https://airing.ursb.me/2life/user/6182/profile_1541174843786.png-2life_face.jpg-46.jpg) lionfox
---
写日记界面，输入不能用拼音打字。

**Comment by airingursb** [comment]
已修复  [#b404f8](https://github.com/oh-bear/2life/commit/b404f84d478a2bfd919e03dc1d3f4c032756c320)

此处需要判断平台。 @lightnate @csfwff
