### ISSUE TITLE
不错，就是不能退出

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#171]
![6110](https://wx.qlogo.cn/mmopen/vi_32/SOuthcM6nYKvSjibeOoicrf3dPbDEpFryydIZaHVpS14OgfibdHUiceXYnibw6IJDcGJQY9bTckdnqiaFnrMb38baYqA/132-46.jpg) 哈特
---
不错，就是不能退出

**Comment by airingursb** [comment]
亲测 iOS 端可以退出登录
