### ISSUE TITLE
匹配功能 泄露隐私

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#172]
![3256](https://wx.qlogo.cn/mmopen/vi_32/1NriaH07cwceRSaRQicEDriaktVpnC7DJ5wS3bQOQgg8lGCY54B6ribcbq0bibw1kMcS4ZZ3SJFQicicnVrbHqHOz1dicg/132-46.jpg) 刘畅
---
匹配功能 泄露隐私

**Comment by airingursb** [comment]
@zyktrcn  跟进一下，与用户取得联系，看看是否为 api 设计问题
