### ISSUE TITLE
匹配页面 UI Bug，导致无法继续使用

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#174]
![6253](https://airing.ursb.me/2life/user/6253/profile_1542117129097.png-2life_face.jpg-46.jpg) 猫咪的城堡
---
小米8，匹配功能有问题，无法匹配，一直停留在“我明白了”界面，点了也没反应，而且显示的东西也仅仅是一个角

**Comment by airingursb** [comment]
已于2.1.5版本修复。
commit：[1d5f04f1aa864fab17f358c281592d3e4528d8a2](https://github.com/oh-bear/2life/commit/1d5f04f1aa864fab17f358c281592d3e4528d8a2)
