### ISSUE TITLE
匹配是实时匹配吗 要双方都在匹配时才能

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#185]
![5162](https://airing.ursb.me/2life/user/5162/img_1541671511586.png-2life_face.jpg-46.jpg) 🍊🍐女亭
---
匹配是实时匹配吗 要双方都在匹配时才能匹配到吗 如果匹配到我的那个人单方面解除匹配 那我也要解除匹配吗

**Comment by airingursb** [comment]
#153
