### ISSUE TITLE
日记为什么是给别人看的？😥 自己的日

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#197]
![5493](https://wx.qlogo.cn/mmopen/vi_32/bCdBMPhbNsIhVUdFf2EaZJa35SHiaIzlLyzxcicABzSEAHeGH3iaqp3kLcDBSSR9ydMo5ibZZvJcEybRxcL1SUhvrw/132-46.jpg) 木心493
---
日记为什么是给别人看的？😥 自己的日记不是自己的隐私么？

**Comment by airingursb** [comment]
可以选择关闭匹配，这样就是纯正的私人日记。
也可以选择关闭同步，这样就是纯正的离线私人日记。

后续有必要添加新手教程
