### ISSUE TITLE
匹配次数有限竟然不提前说明……

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#203]
![7701](https://wx.qlogo.cn/mmopen/vi_32/5yCwk7ibAP9HqBZDPjhicOibBKDu8R1ibxOXu95Xk3Pxc9229foqicfqEo2wWWD5UWevsg7Qmzkg2vXnS4ZkHvFS5wg/132-46.jpg) 紫安
 Brand:, System:, Version:
 --- 
匹配次数有限竟然不提前说明……

**Comment by airingursb** [comment]
提前说明了的- -
