### ISSUE TITLE
网络很好，但上传失败了，希望你们可以尽

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#223]
![8688](https://wx.qlogo.cn/mmopen/vi_32/K0tzZbapYM3EQzvGLdto1AoXoUYYj0nwZ33lcyKEDVqPcmYkiajPPPqStw7BtOgvqW6DmQ3AXbicrPe5GCRxcHdw/132-46.jpg) 青春无极限
 Brand:, System:, Version:
 --- 
网络很好，但上传失败了，希望你们可以尽快解决一下

**Comment by zyktrcn** [comment]
新版本已解决
