### ISSUE TITLE
以往的日记希望可以删除一下哦

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#228]
![8968](https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKzPgF0WqEmiaRcFo7aV0YVCtibuBM76H6MDYCgz6XuvicfoNMW08BGoXVVWHRL8FRh8ndHyQtSDB99Q/132-46.jpg) 缓月
 Brand:, System:, Version:
 --- 
以往的日记希望可以删除一下哦

**Comment by airingursb** [comment]
各平台均有删除日记的功能。。
