### ISSUE TITLE
萌新请教下

### ISSUE THREAD

**Issue by Jee102** [oh-bear/2life#237]
就是喜欢你们设计的UI，想学习下，但是代码为什么微信开发者工具跑不了？

**Comment by airingursb** [comment]
@zyktrcn

**Comment by zyktrcn** [comment]
检查app.json中的pages是否数组形式，有没有加了多余的标点。

**Comment by airingursb** [comment]
@zyktrcn 他私信和我说的是仓库里的 app.json 根本就没有 pages 这个数组= =

**Comment by zyktrcn** [comment]
确认一下是否该仓库：https://github.com/oh-bear/2life-wechat

**Comment by Jee102** [comment]
> 确认一下是否该仓库：https://github.com/oh-bear/2life-wechat

谢谢，原来我下错了。。。。
