### ISSUE TITLE
匹配到的用户的日记质量好低，体验差。

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#45]
![250](https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83erL0RTonibZPp0m9e5qWFoicMCTbrcp8S25GECZRibTHMRXFx7TujY06WIQoFW0aVJC5CWUSf6nNk0bQ/132-46.jpg) 晨曦
---
匹配到的用户的日记质量好低，体验差。

**Comment by airingursb** [comment]
7月下旬做完离线版之后开始推流，提升用户质量 @lightnate
