### ISSUE TITLE
重复发表一篇日志，新建日志失败，想不懂

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#58]
![468](https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJ4q0zKkfcSMg0zmWIjI7Vicvn2UGx648J03MvLx2P78AnIaTlxuN8fE6Jy5k4dqnw890ia6flaaLcA/132-46.jpg) baymax
---
重复发表一篇日志，新建日志失败，想不懂

**Comment by airingursb** [comment]
小程序新版本已修复
