### ISSUE TITLE
测试反馈功能

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#59]
![533](https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLFGzibQXskGYg4bEiav4gtcicxdSwt2606BFgF0RCrtRBIeqhc5TQkQjP4vvic1iaImcfEo2hbjCOeeBw/132-46.jpg) 介质
---
测试反馈功能

**Comment by vTNT** [comment]
大兄弟， 怎么加入你们。

**Comment by airingursb** [comment]
@vTNT 发自我介绍至 airing@ursb.me
