### ISSUE TITLE
匹配完成后如果可以申请查看对方日记或可

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#67]
![1178](https://wx.qlogo.cn/mmopen/vi_32/U7drYhAKfiaQVphXFdvwrgUgLAqricv5DN6tXqInkvhcwvKcTvbCKC2sOmoFR9Ms8fFl3IeAPEeDb7A8An4tUf8w/132-46.jpg) 暖风何时
---
匹配完成后如果可以申请查看对方日记或可以与对方交流就更好了。

**Comment by airingursb** [comment]
#41
