### ISSUE TITLE
设置中的“允许推荐日记”按钮开启后没法

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#68]
![1178](https://wx.qlogo.cn/mmopen/vi_32/U7drYhAKfiaQVphXFdvwrgUgLAqricv5DN6tXqInkvhcwvKcTvbCKC2sOmoFR9Ms8fFl3IeAPEeDb7A8An4tUf8w/132-46.jpg) 暖风何时
---
设置中的“允许推荐日记”按钮开启后没法保存，离开该页面再进来发现按钮还是关闭状态。

**Comment by airingursb** [comment]
已修复
