### ISSUE TITLE
希望添加隐私保护，如Face id / Touch id

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#76]
![1082](https://airing.ursb.me/image/twolife/male.png-46.jpg) 二青
---
有时候手机可能会被别人翻看，但是日记是非常隐私的东西，在iOS上没有办法专门对某一款软件进行加密…所以建议添加软件锁功能，就像支付宝一样，在第一次或者几分钟后打开软件需要输入设定的密码或者验证ID，这样能更好的保护用户隐私

**Comment by airingursb** [comment]
已于2.1.4版本解决
