### ISSUE TITLE
希望能出一个，没写完的日记摁到

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#89]
![1082](https://airing.ursb.me/image/twolife/male.png-46.jpg) 二青
---
希望能出一个，没写完的日记摁到返回键返回时能自动保存或者存为草稿在本地，能重新打开编辑，最不济就返回时给个弹框提示一下说，当返回主界面所写的内容会被清空，
刚刚写了半小时的日记，一下子就没了，找都找不到，哭

**Comment by airingursb** [comment]
#95
