### ISSUE TITLE
推荐日记点不开

### ISSUE THREAD

**Issue by lightnate** [oh-bear/2life#96]
![1171](https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKFZqRxpq9Rz9c6Noaiaz74RNPwKZ9LA7tiaBG8iaJiawPPJE74CchRK4TiaPVBZY3zWgrchpoiaVuq8gFw/132-46.jpg) 吃猫的鱼
---
推荐日记点不开

**Comment by airingursb** [comment]
已修复
